Repository Bisi3asi/Planters, pull requests merged in 2024-04, with the labels that each got.

#5 docs: 기획 ISSUE TEMPLATE 업데이트
  .github/ISSUE_TEMPLATE/기획-issue-template.md
Labels: 💡 수정

#7 docs: 기획 ISSUE TEMPLATE 업데이트
  .github/ISSUE_TEMPLATE/기획-issue-template.md
Labels: 💡 수정

#6 docs: 수정 ISSUE TEMPLATE 작성
  .github/ISSUE_TEMPLATE/수정-issue-template.md
  .gitignore
Labels: 💡 기획

#8 docs: 기획 ISSUE TEMPLATE 업데이트
  .github/ISSUE_TEMPLATE/기획-issue-template.md
Labels: 💡 수정, 💡 기획

#10 docs: 기획 ISSUE TEMPLATE 작성 ISSUE TEMPLATE으로 변경
  .github/ISSUE_TEMPLATE/기획-issue-template.md
  .github/ISSUE_TEMPLATE/수정-issue-template.md
Labels: ⚙️ 시스템

#11 docs: 질의응답 ISSUE TEMPLATE 추가
  .github/ISSUE_TEMPLATE/기획-issue-template.md
  .github/ISSUE_TEMPLATE/질의응답-issue-template.md
Labels: ⚙️ 시스템

#16 docs: README 업데이트
  README.md
Labels: ⚙️ 시스템

#17 feat: all-contributor src
  .all-contributorsrc
Labels: ⚙️ 시스템

#21 docs: README 업데이트
  README.md
Labels: ⚙️ 시스템

#22 docs: README 업데이트
  README.md
Labels: ⚙️ 시스템

#24 CS/Design Pattern:데코레이터 패턴과 프록시 패턴의 차이
  Computer Science/Design Pattern/데코레이터 패턴과 프록시 패턴의 차이.md
Labels: 💡 작성

#28 feat: [요구사항 확인] 현행 시스템 분석
  Certification/정보처리기사/README.md
  Certification/정보처리기사/필기/소프트웨어 설계/[요구사항 확인] 현행 시스템 분석.md
Labels: 💡 작성

#27 chore: 작성 ISSUE TEMPLATE 업데이트
  .github/ISSUE_TEMPLATE/기획-issue-template.md
Labels: ⚙️ 시스템

#35 프로그래머스 SQL 코딩테스트 문제풀이 -[ORACLE / Level 4] 서울에 위치한 식당 목록 출력하기
  Coding Test/SQL/Programmers 문제풀이/[ORACLE, LV4] 서울에 위치한 식당 목록 출력하기.md
Labels: 💡 작성

#33 정보처리기사 소프트웨어 설계 과목 - 2. 요구사항 확인
  Certification/정보처리기사/필기/소프트웨어 설계/[요구사항 확인] 요구사항 확인.md
Labels: 💡 작성

#39 [작성] 정보처리기사 필기 소프트웨어 설계 과목 - 3. 분석 모델 확인
  Certification/정보처리기사/필기/소프트웨어 설계/[요구사항 확인] 분석 모델 확인.md
  Certification/정보처리기사/필기/소프트웨어 설계/[요구사항 확인] 요구사항 확인.md
Labels: 💡 작성

#42 [SpringBoot, Mapping anotation] @RequestMapping
  Tech/Spring/MappingAnotation/@RequestMapping.md
Labels: 💡 작성
